Document: efa
Title: Debian efa Manual
Author: <insert document author here>
Abstract: This manual describes what efa is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/efa/efa.sgml.gz

Format: postscript
Files: /usr/share/doc/efa/efa.ps.gz

Format: text
Files: /usr/share/doc/efa/efa.text.gz

Format: HTML
Index: /usr/share/doc/efa/html/index.html
Files: /usr/share/doc/efa/html/*.html
